### ISSUE TITLE
what is the math behind "lagrange(x, xx)" function?

### ISSUE THREAD

**Issue by capriciousZihao** [pog87/FakeNodes#1]
Hi,

Could you say a few words about the math behind the function _lagrange(x, xx)_. 
In particular, "np.prod(np.matlib.repmat(xx.reshape(m,1),1,n-1) - np.matlib.repmat(x_k,m,1) , axis=1)".

Besides, the return value of "largange(x, xx)" is the reverse of a Vandermonde matrix, am I right?

Thanks a lot.

**Comment by pog87** [comment]
HI, thanks for your interest in out work.

 The function `lagrange(x,xx)` returns the matrix
L_{k,j} = l_j(xx_k)
being l_j(x) the jth [lagrange polynomial](https://en.wikipedia.org/wiki/Lagrange_polynomial) evalued in the kth evaluation point from the vector xx.

The line

```
np.prod(np.matlib.repmat(xx.reshape(m,1),1,n-1) - np.matlib.repmat(x_k,m,1) , axis=1)
```

computes the numerator of the productory  
![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6e2c3a2ab16a8723c0446de6a30da839198fb04b)
evalued in each of the points `xx`.

Since this is a cardinal basis the's no need to form and invert a Vandermonde matrix, with great advantages to the stability.

**Comment by capriciousZihao** [comment]
I see. Thanks : )
